version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/app                 # Bind mount direktori kode dari host ke container
      - /app/tmp               # Tempat file sementara untuk Go build
    ports:
      - "8080:8080"            # Map port aplikasi
    env_file:
      - .env                   # Load environment variables

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: